export const types = {
  login: "[Auth] Login",
  logout: "[Auth] Logout",
  ///////////////////
  uiOpenEmpleadosModal: "[UI] Open employes Modal",
  uiCloseEmpleadosModal: "[UI] Close employes Modal",
  uiOpenPuestosModal: "[UI] Open puestos Modal",
  uiClosePuestosModal: "[UI] Close puestos Modal",
  uiOpenTableModal: "[UI] Open Table Modal",
  uiCloseTableModal: "[UI] Close Table Modal",
  uiOpenBrandModal: "[UI] Open Brand Modal",
  uiCloseBrandModal: "[UI] Close Brand Modal",
  uiOpenSupplierModal: "[UI] Open Supplier Modal",
  uiCloseSupplierModal: "[UI] Close Supplier Modal",
  uiOpenUserModal: "[UI] Open User Modal",
  uiCloseUserModal: "[UI] Close User Modal",
  uiOpenRolModal: "[UI] Open Rol Modal",
  uiCloseRolModal: "[UI] Close Rol Modal",
  uiOpenConsecutivoModal: "[UI] Open Consecutivo Modal",
  uiCloseConsecutivoModal: "[UI] Close Consecutivo Modal",
  uiOpenUnidadMedidaModal: "[UI] Open UnidadMedida Modal",
  uiCloseUnidadMedidaModal: "[UI] Close UnidadMedida Modal",
  uiOpenCountryModal: "[UI] Open Country Modal",
  uiCloseCountryModal: "[UI] Close Country Modal",
  uiOpenComestiblesModal: "[UI] Open Comestibles Modal",
  uiCloseComestiblesModal: "[UI] Close Comestibles Modal",
  uiOpenEquiposModal: "[UI] Open Equipos Modal",
  uiCloseEquiposModal: "[UI] Close Equipos Modal",
  uiOpenTecnologiaModal: "[UI] Open Tecnologia Modal",
  uiCloseTecnologiaModal: "[UI] Close Tecnologia Modal",
  uiOpenLimpiezaModal: "[UI] Open Limpieza Modal",
  uiCloseLimpiezaModal: "[UI] Close Limpieza Modal",
  uiOpenDesechablesModal: "[UI] Open Desechables Modal",
  uiCloseDesechablesModal: "[UI] Close Desechables Modal",
  //////////////////
  setActiveEmployee: "[Employees] Set Active Employee",
  removeActiveEmployee: "[Employees] Remove Active Employee",
  addEmployee: "[Employees] Add new Employee",
  editEmployee: "[Employees] Edit Employee",
  deleteEmployee: "[Employees] Delete Employee",
  employeesLoaded: "[Employees] Loaded",
  /////////////////
  setActiveJob: "[Jobs] Set Active Job",
  removeActiveJob: "[Jobs] Remove Active Job",
  addJob: "[Jobs] Add new Job",
  editJob: "[Jobs] Edit Job",
  deleteJob: "[Jobs] Delete Job",
  jobsLoaded: "[JOBS] Loaded",
  /////////////////
  setActiveTable: "[TABLE] Set Active Table",
  removeActiveTable: "[TABLE] Remove Active Table",
  addTable: "[TABLE] Add new Table",
  editTable: "[TABLE] Edit Table",
  deleteTable: "[TABLE] Delete Job",
  tableLoaded: "[TABLE] Loading Tables",
  /////////////////
  setActiveBrand: "[BRAND] Set Active brand",
  removeActiveBrand: "[BRAND] Remove Active brand",
  addBrand: "[BRAND] Add new brand",
  editBrand: "[BRAND] Edit brand",
  deleteBrand: "[BRAND] Delete Job",
  brandLoaded: "[BRAND] Loading brands",
  /////////////////
  setActiveSupplier: "[SUPPLIERS] Set Active supplier",
  removeActiveSupplier: "[SUPPLIERS] Remove Active supplier",
  addSupplier: "[SUPPLIERS] Add new supplier",
  editSupplier: "[SUPPLIERS] Edit supplier",
  deleteSupplier: "[SUPPLIERS] Delete Job",
  supplierLoaded: "[SUPPLIERS] Loading suppliers",
  /////////////////
  setActiveUser: "[USERS] Set Active User",
  removeActiveUser: "[USERS] Remove Active User",
  addUser: "[USERS] Add new User",
  editUser: "[USERS] Edit User",
  deleteUser: "[USERS] Delete User",
  userLoaded: "[USERS] Loading Users",
  /////////////////
  setActiveConsecutivos: "[CONSECUTIVOS] Set Active Consecutivos",
  removeActiveConsecutivos: "[CONSECUTIVOS] Remove Active Consecutivos",
  addConsecutivos: "[CONSECUTIVOS] Add new Consecutivos",
  editConsecutivos: "[CONSECUTIVOS] Edit Consecutivos",
  deleteConsecutivos: "[CONSECUTIVOS] Delete Consecutivo",
  consecutivosLoaded: "[CONSECUTIVOS] Loading Consecutivo",
  /////////////////
  setActiveCountry: "[COUNTRY] Set Active Country",
  removeActiveCountry: "[COUNTRY] Remove Active Country",
  addCountry: "[COUNTRY] Add new Country",
  editCountry: "[COUNTRY] Edit Country",
  deleteCountry: "[COUNTRY] Delete Country",
  countryLoaded: "[COUNTRY] Loading Country",
  /////////////////
  setActiveRol: "[ROLS] Set Active Rol",
  removeActiveRol: "[ROLS] Remove Active Rol",
  addRol: "[ROLS] Add new Rol",
  editRol: "[ROLS] Edit Rol",
  deleteRol: "[ROLS] Delete Rol",
  rolLoaded: "[ROLS] Loading Rols",
  /////////////////
  setActiveUnidadMedida: "[UNIDADES_MEDIDA] Set Active UnidadMedida",
  removeActiveUnidadMedida: "[UNIDADES_MEDIDA] Remove Active UnidadMedida",
  addUnidadMedida: "[UNIDADES_MEDIDA] Add new UnidadMedida",
  editUnidadMedida: "[UNIDADES_MEDIDA] Edit UnidadMedida",
  deleteUnidadMedida: "[UNIDADES_MEDIDA] Delete UnidadMedida",
  unidadMedidaLoaded: "[UNIDADES_MEDIDA] Loading UnidadMedidas",
  /////////////////
  bitacoraLoaded: "[BITACORA] Bitacora Loaded",
  /////////////////
  setActiveComestibles: "[COMESTIBLES] Set Active Comestibles",
  removeActiveComestibles: "[COMESTIBLES] Remove Active Comestibles",
  addComestibles: "[COMESTIBLES] Add new Comestibles",
  editComestibles: "[COMESTIBLES] Edit Comestibles",
  deleteComestibles: "[COMESTIBLES] Delete Comestibles",
  comestiblesLoaded: "[COMESTIBLES] Loading Comestibless",
  /////////////////
  setActiveDesechables: "[DESECHABLES] Set Active Desechables",
  removeActiveDesechables: "[DESECHABLES] Remove Active Desechables",
  addDesechables: "[DESECHABLES] Add new Desechables",
  editDesechables: "[DESECHABLES] Edit Desechables",
  deleteDesechables: "[DESECHABLES] Delete Desechables",
  desechablesLoaded: "[DESECHABLES] Loading Desechables",
  /////////////////
  setActiveLimpieza: "[Limpieza] Set Active Limpieza",
  removeActiveLimpieza: "[Limpieza] Remove Active Limpieza",
  addLimpieza: "[Limpieza] Add new Limpieza",
  editLimpieza: "[Limpieza] Edit Limpieza",
  deleteLimpieza: "[Limpieza] Delete Limpieza",
  limpiezaLoaded: "[Limpieza] Loading Limpieza",
  /////////////////
  setActiveTecnologia: "[Tecnologia] Set Active Tecnologia",
  removeActiveTecnologia: "[Tecnologia] Remove Active Tecnologia",
  addTecnologia: "[Tecnologia] Add new Tecnologia",
  editTecnologia: "[Tecnologia] Edit Tecnologia",
  deleteTecnologia: "[Tecnologia] Delete Tecnologia",
  tecnologiaLoaded: "[Tecnologia] Loading Tecnologia",
  /////////////////
  setActiveEquipos: "[Equipos] Set Active Equipos",
  removeActiveEquipos: "[Equipos] Remove Active Equipos",
  addEquipos: "[Equipos] Add new Equipos",
  editEquipos: "[Equipos] Edit Equipos",
  deleteEquipos: "[Equipos] Delete Equipos",
  equiposLoaded: "[Equipos] Loading Equipos",
};
