export const types = {
  login: "[Auth] Login",
  logout: "[Auth] Logout",
  ///////////////////
  uiOpenEmpleadosModal: "[UI] Open employes Modal",
  uiCloseEmpleadosModal: "[UI] Close employes Modal",
  uiOpenPuestosModal: "[UI] Open puestos Modal",
  uiClosePuestosModal: "[UI] Close puestos Modal",
  uiOpenTableModal: "[UI] Open Table Modal",
  uiCloseTableModal: "[UI] Close Table Modal",
  uiOpenBrandModal: "[UI] Open Brand Modal",
  uiCloseBrandModal: "[UI] Close Brand Modal",
  uiOpenSupplierModal: "[UI] Open Supplier Modal",
  uiCloseSupplierModal: "[UI] Close Supplier Modal",
  uiOpenUserModal: "[UI] Open User Modal",
  uiCloseUserModal: "[UI] Close User Modal",
  uiOpenRolModal: "[UI] Open Rol Modal",
  uiCloseRolModal: "[UI] Close Rol Modal",
  uiOpenConsecutivoModal: "[UI] Open Consecutivo Modal",
  uiCloseConsecutivoModal: "[UI] Close Consecutivo Modal",
  uiOpenUnidadMedidaModal: "[UI] Open UnidadMedida Modal",
  uiCloseUnidadMedidaModal: "[UI] Close UnidadMedida Modal",
  uiOpenCountryModal: "[UI] Open Country Modal",
  uiCloseCountryModal: "[UI] Close Country Modal",
  uiOpenComestiblesModal: "[UI] Open Comestibles Modal",
  uiCloseComestiblesModal: "[UI] Close Comestibles Modal",
  uiOpenEquiposModal: "[UI] Open Equipos Modal",
  uiCloseEquiposModal: "[UI] Close Equipos Modal",
  uiOpenTecnologiaModal: "[UI] Open Tecnologia Modal",
  uiCloseTecnologiaModal: "[UI] Close Tecnologia Modal",
  uiOpenLimpiezaModal: "[UI] Open Limpieza Modal",
  uiCloseLimpiezaModal: "[UI] Close Limpieza Modal",
  uiOpenDesechablesModal: "[UI] Open Desechables Modal",
  uiCloseDesechablesModal: "[UI] Close Desechables Modal",
  uiOpenBuffetModal: "[UI] Open Buffet Modal",
  uiCloseBuffetModal: "[UI] Close Buffet Modal",
  uiOpenEspecialidadesModal: "[UI] Open Especialidades Modal",
  uiCloseEspecialidadesModal: "[UI] Close Especialidades Modal",
  uiOpenBebidasCalientesModal: "[UI] Open Bebidas Calientes Modal",
  uiCloseBebidasCalientesModal: "[UI] Close Bebidas Calientes Modal",
  uiOpenBebidasHeladasModal: "[UI] Open Bebidas Heladas Modal",
  uiCloseBebidasHeladasModal: "[UI] Close Bebidas Heladas Modal",
  uiOpenBebidasGaseosasModal: "[UI] Open Bebidas Gaseosas Modal",
  uiCloseBebidasGaseosasModal: "[UI] Close Bebidas Gaseosas Modal",

  uiOpenLicoresModal: "[UI] Open Licores Modal",
  uiCloseLicoresModal: "[UI] Close Licores Modal",

  uiOpenVinosModal: "[UI] Open Vinos Modal",
  uiCloseVinosModal: "[UI] Close Vinos Modal",
  //////////////////
  setActiveEmployee: "[Employees] Set Active Employee",
  removeActiveEmployee: "[Employees] Remove Active Employee",
  addEmployee: "[Employees] Add new Employee",
  editEmployee: "[Employees] Edit Employee",
  deleteEmployee: "[Employees] Delete Employee",
  employeesLoaded: "[Employees] Loaded",
  /////////////////
  setActiveJob: "[Jobs] Set Active Job",
  removeActiveJob: "[Jobs] Remove Active Job",
  addJob: "[Jobs] Add new Job",
  editJob: "[Jobs] Edit Job",
  deleteJob: "[Jobs] Delete Job",
  jobsLoaded: "[JOBS] Loaded",
  /////////////////
  setActiveTable: "[TABLE] Set Active Table",
  removeActiveTable: "[TABLE] Remove Active Table",
  addTable: "[TABLE] Add new Table",
  editTable: "[TABLE] Edit Table",
  deleteTable: "[TABLE] Delete Job",
  tableLoaded: "[TABLE] Loading Tables",
  /////////////////
  setActiveBrand: "[BRAND] Set Active brand",
  removeActiveBrand: "[BRAND] Remove Active brand",
  addBrand: "[BRAND] Add new brand",
  editBrand: "[BRAND] Edit brand",
  deleteBrand: "[BRAND] Delete Job",
  brandLoaded: "[BRAND] Loading brands",
  /////////////////
  setActiveSupplier: "[SUPPLIERS] Set Active supplier",
  removeActiveSupplier: "[SUPPLIERS] Remove Active supplier",
  addSupplier: "[SUPPLIERS] Add new supplier",
  editSupplier: "[SUPPLIERS] Edit supplier",
  deleteSupplier: "[SUPPLIERS] Delete Job",
  supplierLoaded: "[SUPPLIERS] Loading suppliers",
  /////////////////
  setActiveUser: "[USERS] Set Active User",
  removeActiveUser: "[USERS] Remove Active User",
  addUser: "[USERS] Add new User",
  editUser: "[USERS] Edit User",
  deleteUser: "[USERS] Delete User",
  userLoaded: "[USERS] Loading Users",
  /////////////////
  setActiveConsecutivos: "[CONSECUTIVOS] Set Active Consecutivos",
  removeActiveConsecutivos: "[CONSECUTIVOS] Remove Active Consecutivos",
  addConsecutivos: "[CONSECUTIVOS] Add new Consecutivos",
  editConsecutivos: "[CONSECUTIVOS] Edit Consecutivos",
  deleteConsecutivos: "[CONSECUTIVOS] Delete Consecutivo",
  consecutivosLoaded: "[CONSECUTIVOS] Loading Consecutivo",
  /////////////////
  setActiveCountry: "[COUNTRY] Set Active Country",
  removeActiveCountry: "[COUNTRY] Remove Active Country",
  addCountry: "[COUNTRY] Add new Country",
  editCountry: "[COUNTRY] Edit Country",
  deleteCountry: "[COUNTRY] Delete Country",
  countryLoaded: "[COUNTRY] Loading Country",
  /////////////////
  setActiveRol: "[ROLS] Set Active Rol",
  removeActiveRol: "[ROLS] Remove Active Rol",
  addRol: "[ROLS] Add new Rol",
  editRol: "[ROLS] Edit Rol",
  deleteRol: "[ROLS] Delete Rol",
  rolLoaded: "[ROLS] Loading Rols",
  /////////////////
  setActiveUnidadMedida: "[UNIDADES_MEDIDA] Set Active UnidadMedida",
  removeActiveUnidadMedida: "[UNIDADES_MEDIDA] Remove Active UnidadMedida",
  addUnidadMedida: "[UNIDADES_MEDIDA] Add new UnidadMedida",
  editUnidadMedida: "[UNIDADES_MEDIDA] Edit UnidadMedida",
  deleteUnidadMedida: "[UNIDADES_MEDIDA] Delete UnidadMedida",
  unidadMedidaLoaded: "[UNIDADES_MEDIDA] Loading UnidadMedidas",
  /////////////////
  bitacoraLoaded: "[BITACORA] Bitacora Loaded",
  /////////////////
  setActiveComestibles: "[COMESTIBLES] Set Active Comestibles",
  removeActiveComestibles: "[COMESTIBLES] Remove Active Comestibles",
  addComestibles: "[COMESTIBLES] Add new Comestibles",
  editComestibles: "[COMESTIBLES] Edit Comestibles",
  deleteComestibles: "[COMESTIBLES] Delete Comestibles",
  comestiblesLoaded: "[COMESTIBLES] Loading Comestibless",
  /////////////////
  setActiveDesechables: "[DESECHABLES] Set Active Desechables",
  removeActiveDesechables: "[DESECHABLES] Remove Active Desechables",
  addDesechables: "[DESECHABLES] Add new Desechables",
  editDesechables: "[DESECHABLES] Edit Desechables",
  deleteDesechables: "[DESECHABLES] Delete Desechables",
  desechablesLoaded: "[DESECHABLES] Loading Desechables",
  /////////////////
  setActiveLimpieza: "[Limpieza] Set Active Limpieza",
  removeActiveLimpieza: "[Limpieza] Remove Active Limpieza",
  addLimpieza: "[Limpieza] Add new Limpieza",
  editLimpieza: "[Limpieza] Edit Limpieza",
  deleteLimpieza: "[Limpieza] Delete Limpieza",
  limpiezaLoaded: "[Limpieza] Loading Limpieza",
  /////////////////
  setActiveTecnologia: "[Tecnologia] Set Active Tecnologia",
  removeActiveTecnologia: "[Tecnologia] Remove Active Tecnologia",
  addTecnologia: "[Tecnologia] Add new Tecnologia",
  editTecnologia: "[Tecnologia] Edit Tecnologia",
  deleteTecnologia: "[Tecnologia] Delete Tecnologia",
  tecnologiaLoaded: "[Tecnologia] Loading Tecnologia",
  /////////////////
  setActiveEquipos: "[Equipos] Set Active Equipos",
  removeActiveEquipos: "[Equipos] Remove Active Equipos",
  addEquipos: "[Equipos] Add new Equipos",
  editEquipos: "[Equipos] Edit Equipos",
  deleteEquipos: "[Equipos] Delete Equipos",
  equiposLoaded: "[Equipos] Loading Equipos",
  /////////////////
  setActiveBuffets: "[Buffets] Set Active Buffets",
  removeActiveBuffets: "[Buffets] Remove Active Buffets",
  addBuffets: "[Buffets] Add new Buffets",
  editBuffets: "[Buffets] Edit Buffets",
  deleteBuffets: "[Buffets] Delete Buffets",
  buffetsLoaded: "[Buffets] Loading Buffets",
  /////////////////
  setActiveEspecialidad: "[Especialidad] Set Active Especialidad",
  removeActiveEspecialidad: "[Especialidad] Remove Active Especialidad",
  addEspecialidad: "[Especialidad] Add new Especialidad",
  editEspecialidad: "[Especialidad] Edit Especialidad",
  deleteEspecialidad: "[Especialidad] Delete Especialidad",
  especialidadLoaded: "[Especialidad] Loading Especialidad",
  /////////////////
  setActiveBebidaCaliente: "[BebidaCaliente] Set Active BebidaCaliente",
  removeActiveBebidaCaliente: "[BebidaCaliente] Remove Active BebidaCaliente",
  addBebidaCaliente: "[BebidaCaliente] Add new BebidaCaliente",
  editBebidaCaliente: "[BebidaCaliente] Edit BebidaCaliente",
  deleteBebidaCaliente: "[BebidaCaliente] Delete BebidaCaliente",
  bebidaCalienteLoaded: "[BebidaCaliente] Loading BebidaCaliente",
  /////////////////
  setActiveBebidaHelada: "[BebidaHelada] Set Active BebidaHelada",
  removeActiveBebidaHelada: "[BebidaHelada] Remove Active BebidaHelada",
  addBebidaHelada: "[BebidaHelada] Add new BebidaHelada",
  editBebidaHelada: "[BebidaHelada] Edit BebidaHelada",
  deleteBebidaHelada: "[BebidaHelada] Delete BebidaHelada",
  bebidaHeladaLoaded: "[BebidaHelada] Loading BebidaHelada",
  /////////////////
  setActiveBebidaGaseosa: "[BebidaGaseosa] Set Active BebidaGaseosa",
  removeActiveBebidaGaseosa: "[BebidaGaseosa] Remove Active BebidaGaseosa",
  addBebidaGaseosa: "[BebidaGaseosa] Add new BebidaGaseosa",
  editBebidaGaseosa: "[BebidaGaseosa] Edit BebidaGaseosa",
  deleteBebidaGaseosa: "[BebidaGaseosa] Delete BebidaGaseosa",
  bebidaGaseosaLoaded: "[BebidaGaseosa] Loading BebidaGaseosa",
  /////////////////
  setActiveLicores: "[Licores] Set Active Licores",
  removeActiveLicores: "[Licores] Remove Active Licores",
  addLicores: "[Licores] Add new Licores",
  editLicores: "[Licores] Edit Licores",
  deleteLicores: "[Licores] Delete Licores",
  licoresLoaded: "[Licores] Loading Licores",
  /////////////////
  setActiveVinos: "[Vinos] Set Active Vinos",
  removeActiveVinos: "[Vinos] Remove Active Vinos",
  addVinos: "[Vinos] Add new Vinos",
  editVinos: "[Vinos] Edit Vinos",
  deleteVinos: "[Vinos] Delete Vinos",
  vinosLoaded: "[Vinos] Loading Vinos",
};
