export const types = {
  login: "[Auth] Login",
  logout: "[Auth] Logout",
  ///////////////////
  uiOpenEmpleadosModal: "[UI] Open employes Modal",
  uiCloseEmpleadosModal: "[UI] Close employes Modal",
  uiOpenPuestosModal: "[UI] Open puestos Modal",
  uiClosePuestosModal: "[UI] Close puestos Modal",
  uiOpenTableModal: "[UI] Open Table Modal",
  uiCloseTableModal: "[UI] Close Table Modal",
  //////////////////
  setActiveEmployee: "[Employees] Set Active Employee",
  removeActiveEmployee: "[Employees] Remove Active Employee",
  addEmployee: "[Employees] Add new Employee",
  editEmployee: "[Employees] Edit Employee",
  deleteEmployee: "[Employees] Delete Employee",
  employeesLoaded: "[Employees] Loaded",
  /////////////////
  setActiveJob: "[Jobs] Set Active Job",
  removeActiveJob: "[Jobs] Remove Active Job",
  addJob: "[Jobs] Add new Job",
  editJob: "[Jobs] Edit Job",
  deleteJob: "[Jobs] Delete Job",
  jobsLoaded: "[JOBS] Loaded",
  /////////////////
  setActiveTable: "[TABLE] Set Active Table",
  removeActiveTable: "[TABLE] Remove Active Table",
  addTable: "[TABLE] Add new Table",
  editTable: "[TABLE] Edit Table",
  deleteTable: "[TABLE] Delete Job",
  tableLoaded: "[TABLE] Loading Tables",
  /////////////////
  setActivesupplier: "[BRAND] Set Active brand",
  removeActiveBrand: "[BRAND] Remove Active brand",
  addBrand: "[BRAND] Add new brand",
  editBrand: "[BRAND] Edit brand",
  deleteBrand: "[BRAND] Delete Job",
  brandLoaded: "[BRAND] Loading brands",
  /////////////////
  setActiveSupplier: "[SUPPLIERS] Set Active supplier",
  removeActiveSupplier: "[SUPPLIERS] Remove Active supplier",
  addSupplier: "[SUPPLIERS] Add new supplier",
  editSupplier: "[SUPPLIERS] Edit supplier",
  deleteSupplier: "[SUPPLIERS] Delete Job",
  supplierLoaded: "[SUPPLIERS] Loading suppliers",
  /////////////////
  setActiveUser: "[USERS] Set Active User",
  removeActiveUser: "[USERS] Remove Active User",
  addUser: "[USERS] Add new User",
  editUser: "[USERS] Edit User",
  deleteUser: "[USERS] Delete User",
  userLoaded: "[USERS] Loading Users",
  /////////////////
  setActiveConsecutivos: "[CONSECUTIVOS] Set Active Consecutivos",
  removeActiveConsecutivos: "[CONSECUTIVOS] Remove Active Consecutivos",
  addConsecutivos: "[CONSECUTIVOS] Add new Consecutivos",
  editConsecutivos: "[CONSECUTIVOS] Edit Consecutivos",
  deleteConsecutivos: "[CONSECUTIVOS] Delete Consecutivo",
  consecutivosLoaded: "[CONSECUTIVOS] Loading Consecutivo",
  /////////////////
  setActiveCountry: "[COUNTRY] Set Active Country",
  removeActiveCountry: "[COUNTRY] Remove Active Country",
  addCountry: "[COUNTRY] Add new Country",
  editCountry: "[COUNTRY] Edit Country",
  deleteCountry: "[COUNTRY] Delete Country",
  countryLoaded: "[COUNTRY] Loading Country",
  /////////////////
  setActiveRol: "[ROLS] Set Active Rol",
  removeActiveRol: "[ROLS] Remove Active Rol",
  addRol: "[ROLS] Add new Rol",
  editRol: "[ROLS] Edit Rol",
  deleteRol: "[ROLS] Delete Rol",
  rolLoaded: "[ROLS] Loading Rols",
  /////////////////
  setActiveUnidadMedida: "[UNIDADES_MEDIDA] Set Active UnidadMedida",
  removeActiveUnidadMedida: "[UNIDADES_MEDIDA] Remove Active UnidadMedida",
  addUnidadMedida: "[UNIDADES_MEDIDA] Add new UnidadMedida",
  editUnidadMedida: "[UNIDADES_MEDIDA] Edit UnidadMedida",
  deleteUnidadMedida: "[UNIDADES_MEDIDA] Delete UnidadMedida",
  unidadMedidaLoaded: "[UNIDADES_MEDIDA] Loading UnidadMedidas",
  /////////////////
};
